### ISSUE TITLE
Hi, I have successfully built Ardupilotcustom, but getting errors in qgroundcontrol? Please fix it.

### ISSUE THREAD

**Issue by kryptoniancode** [angelopassaro/SEC-UAV#2]
@angelopassaro 
Can you please fix it?

**Comment by Phanx00** [comment]
Hi, what error do you have? I haven't worked on this repo for 3 years so I don't know if I can fix it

**Comment by kryptoniancode** [comment]
Hi,
It okay. I have finished it by creating encryption in ardupilot and decryption in tcpserver and completed the task.
I have used this https://github.com/aniskoubaa/mavsec
